version: "3"

networks:
  kafka-connect-sample-net:
    name: kafka-connect-sample-net
    driver: bridge

services:
  sftp:
    image: atmoz/sftp
    container_name: sftp-server
    restart: unless-stopped
    networks:
      - kafka-connect-sample-net
    ports:
        - "2222:22"
    command: sftpuser:sftppassword:::sink-output
  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    networks:
      - kafka-connect-sample-net
    ports:
     - "5432:5432"
    volumes:
      - "./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf"
      - "./postgresql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
     POSTGRES_PASSWORD: postgres
  elasticsearch:
    image: elasticsearch:8.1.2
    container_name: elasticsearch
    restart: unless-stopped
    networks:
      - kafka-connect-sample-net
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node