insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (1, 'Enterprise-wide composite strategy', 8, true);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (2, 'Cloned disintermediate project', 8, true);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (3, 'Reduced client-driven info-mediaries', 10, false);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (4, 'Profound even-keeled hardware', 6, false);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (5, 'Multi-channelled empowering process improvement', 6, true);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (6, 'Public-key high-level encoding', 9, false);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (7, 'Profound well-modulated function', 10, false);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (8, 'Profit-focused intermediate adapter', 5, true);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (9, 'Synergized optimizing parallelism', 2, true);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (10, 'Exclusive bi-directional success', 10, true);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (11, 'Ergonomic zero tolerance capability', 5, false);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (12, 'Vision-oriented bifurcated database', 6, false);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (13, 'Multi-layered composite local area network', 7, true);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (14, 'Operative human-resource adapter', 2, false);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (15, 'Programmable well-modulated throughput', 7, false);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (16, 'Expanded demand-driven forecast', 2, true);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (17, 'Distributed system-worthy methodology', 7, true);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (18, 'Future-proofed actuating knowledge user', 3, true);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (19, 'Assimilated context-sensitive standardization', 6, false);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (20, 'Right-sized motivating extranet', 6, true);
