insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (101, 'Persistent tangible infrastructure', 9, false);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (102, 'Distributed real-time ability', 4, false);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (103, 'Decentralized mobile analyzer', 2, true);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (104, 'Total neutral process improvement', 8, true);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (105, 'Upgradable 4th generation instruction set', 9, true);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (106, 'Down-sized tertiary architecture', 2, true);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (107, 'Open-source solution-oriented matrix', 3, false);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (108, 'Multi-lateral contextually-based methodology', 3, true);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (109, 'Exclusive 24/7 knowledge user', 9, true);
insert into mkt_promotions (promotion_id, promotion_name, promotion_discount_rate, is_active) values (110, 'Fully-configurable reciprocal alliance', 3, true);
