spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            spring.application.name: kafka-streams-iq-basic-sample
            configuration:
              commit.interval.ms: 1000
              
              
      bindings:
        process-out-0:
          destination: product-counts
        process-in-0:
          destination: products
