create table if not exists people_addresses (
	address_id VARCHAR(50),
	person_id VARCHAR(50),
	address VARCHAR(50),
	city VARCHAR(50),
	postal_code VARCHAR(50)
);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3001, 2001, '4095 Waubesa Avenue', 'Priekule', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3002, 2002, '2 Schmedeman Street', 'Nantes', '44036 CEDEX 1');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3003, 2003, '496 Village Green Terrace', 'Dingjiayao', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3004, 2004, '998 Hoard Crossing', 'Qorveh', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3005, 2005, '9 Coolidge Hill', 'Bali', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3006, 2006, '1061 Lunder Parkway', 'Novki', '601340');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3007, 2007, '124 Logan Alley', 'Spasskoye', '606466');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3008, 2008, '943 Straubel Drive', 'Non Sung', '30160');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3009, 2009, '2504 Hoffman Alley', 'Lemahputih', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3010, 2010, '0291 Sugar Circle', 'Rantau', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3011, 2011, '2 Fieldstone Street', 'Głubczyce', '48-100');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3012, 2012, '16 Lakewood Gardens Place', 'Wushan', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3013, 2013, '42 Continental Road', 'Bystra', '34-382');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3014, 2014, '26 Buell Lane', 'Jiyizhuang', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3015, 2015, '289 Hayes Plaza', 'Kalisari', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3016, 2016, '790 Delaware Trail', 'Fukou', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3017, 2017, '9124 Cody Hill', 'Zhongxin', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3018, 2018, '33 Gateway Junction', 'Kilafors', '823 80');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3019, 2019, '49705 Buell Way', 'Taipingchuan', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3020, 2020, '39 Lakeland Way', 'Bichura', '671360');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3021, 2021, '46 Mallory Circle', 'San Esteban', '2706');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3022, 2022, '828 Homewood Hill', 'Kaolack', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3023, 2023, '7 Twin Pines Trail', 'Shuangxiqiao', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3024, 2024, '26 Elgar Junction', 'Sarykemer', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3025, 2025, '10 Westerfield Center', 'Changxing', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3026, 2026, '73755 Superior Crossing', 'Daidaon', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3027, 2027, '40758 Cottonwood Pass', 'Tanahedang', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3028, 2028, '3306 Hintze Lane', 'Jambangan', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3029, 2029, '4491 Emmet Way', 'Darpas', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3030, 2030, '30996 Thackeray Hill', 'Peyima', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3031, 2031, '789 Upham Drive', 'Buenos Aires', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3032, 2032, '68561 Eastlawn Way', 'Banjar Ambengan', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3033, 2033, '5472 Lindbergh Alley', 'Sremski Karlovci', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3034, 2034, '333 Mcbride Way', 'General Alvear', '3361');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3035, 2035, '818 Almo Court', 'Zvečan', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3036, 2036, '2 Jackson Way', 'Chavarría', '3474');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3037, 2037, '6445 Michigan Trail', 'Sohbatpur', '80501');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3038, 2038, '4045 Pierstorff Junction', 'Novonukutskiy', '450049');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3039, 2039, '648 Independence Center', 'Kelungkung', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3040, 2040, '4456 Erie Way', 'Plaški', '47304');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3041, 2041, '3210 Sullivan Parkway', 'Bailizhou', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3042, 2042, '315 Arkansas Lane', 'Las Palmas', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3043, 2043, '43683 Esker Lane', 'Fort Wayne', '46857');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3044, 2044, '50 Moose Street', 'Chengbei', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3045, 2045, '5 Stoughton Place', 'Nzega', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3046, 2046, '016 Lawn Alley', 'Kawengan', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3047, 2047, '06224 Welch Way', 'Dallas', '75387');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3048, 2048, '545 Petterle Street', 'Jäppilä', '77570');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3049, 2049, '444 Columbus Hill', 'Denver', '80279');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3050, 2050, '04451 Ruskin Junction', 'Laï', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3051, 2051, '9 Hoepker Place', 'Krupanj', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3052, 2052, '78196 Brown Circle', 'Baculin', '1060');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3053, 2053, '4 Derek Lane', 'Miraflores', '1495-048');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3054, 2054, '026 Summerview Place', 'Batangan', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3055, 2055, '5 Lake View Drive', 'Peuhaq', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3056, 2056, '70532 Mitchell Street', 'Loma Bonita', '52740');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3057, 2057, '070 Fremont Avenue', 'Yangjiang', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3058, 2058, '8 Portage Alley', 'Beaconsfield', 'H9W');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3059, 2059, '21671 Corry Avenue', 'Cullhuas', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3060, 2060, '0 Crowley Junction', 'Boniewo', '87-851');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3061, 2061, '556 Hallows Plaza', 'Sopron', '9404');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3062, 2062, '69199 3rd Alley', 'Panaoti', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3063, 2063, '90297 Kipling Drive', 'Sizao', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3064, 2064, '3 Dottie Street', 'Sung Noen', '30170');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3065, 2065, '118 Bayside Pass', 'Vale de Figueira', '2695-584');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3066, 2066, '9 Bellgrove Place', 'Pacatuba', '49970-000');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3067, 2067, '26030 Sycamore Court', 'Porto Feliz', '18540-000');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3068, 2068, '1 Atwood Alley', 'Chaiyaphum', '17140');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3069, 2069, '40743 Sloan Crossing', 'Toba', '916-0013');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3070, 2070, '54 Rockefeller Plaza', 'El Plan', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3071, 2071, '29739 Sycamore Point', 'Taradale', '4183');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3072, 2072, '9 Clarendon Avenue', 'Grabów', '99-150');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3073, 2073, '51815 Cody Court', 'Lochovice', '267 23');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3074, 2074, '7538 Melody Parkway', 'Ajaccio', '20195 CEDEX 1');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3075, 2075, '01617 Hagan Pass', 'Bongued', '5605');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3076, 2076, '88 Del Mar Park', 'Bykhaw', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3077, 2077, '67 3rd Drive', 'San Antonio', '78220');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3078, 2078, '7325 Trailsway Court', 'Beaverton', '97075');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3079, 2079, '17446 Forest Run Pass', 'Jinshiqiao', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3080, 2080, '299 Larry Junction', 'Gardanne', '13548 CEDEX');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3081, 2081, '0 Sunnyside Trail', 'Yabēlo', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3082, 2082, '15091 Stuart Avenue', 'Capitán Solari', '3515');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3083, 2083, '39592 Lakewood Gardens Road', 'Flen', '642 24');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3084, 2084, '14441 Saint Paul Park', 'Krasnystaw', '22-300');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3085, 2085, '400 Sauthoff Way', 'Magdalena', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3086, 2086, '51123 Summer Ridge Crossing', 'Knivsta', '741 24');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3087, 2087, '94 Pierstorff Hill', 'Tandil', '7000');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3088, 2088, '55 Knutson Pass', 'Balaoang', '2509');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3089, 2089, '341 Declaration Lane', 'Poręba Spytkowska', '32-865');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3090, 2090, '23660 Clove Pass', 'Tongjing', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3091, 2091, '3698 Jana Junction', 'Washington', '20470');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3092, 2092, '60 Autumn Leaf Junction', 'Orlando', '32819');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3093, 2093, '816 Crescent Oaks Street', 'Miaoxi', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3094, 2094, '810 Hoepker Hill', 'Loučná nad Desnou', '788 11');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3095, 2095, '429 3rd Point', '‘Alāqahdārī Kirān wa Munjān', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3096, 2096, '12 6th Drive', 'Cradock', '5884');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3097, 2097, '6239 Loomis Junction', 'Nongba', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3098, 2098, '4 Holy Cross Pass', 'Vannes', '56019 CEDEX');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3099, 2099, '3664 Hanson Trail', 'Jetis', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3100, 2100, '51420 Riverside Place', 'Tomioka', '999-8524');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3101, 2001, '32 Oneill Center', 'Abaeté', '35620-000');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3102, 2002, '13 Bluestem Point', 'Ḩablah', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3103, 2003, '451 Nelson Parkway', 'Malitubog', '9413');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3104, 2004, '6 Canary Court', 'Ampeleíes', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3105, 2005, '28603 Dennis Crossing', 'Ankaran', '6000');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3106, 2006, '436 Delladonna Crossing', 'San Lorenzo', '56190');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3107, 2007, '9114 Bay Hill', 'Coxim', '79400-000');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3108, 2008, '777 Kipling Trail', 'Arras', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3109, 2009, '657 Sunfield Terrace', 'Gambang', '26340');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3110, 2010, '1 Oak Valley Trail', 'Tubel', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3111, 2011, '51308 Lakewood Gardens Court', 'Guanzhuang', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3112, 2012, '29 Little Fleur Way', 'Rongkou', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3113, 2013, '0461 Hansons Drive', 'La Quebrada', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3114, 2014, '60 Mariners Cove Pass', 'Khantaghy', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3115, 2015, '0234 Sycamore Avenue', 'Hobor', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3116, 2016, '847 Cody Junction', 'Varāmīn', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3117, 2017, '14442 Mifflin Hill', 'San Isidro', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3118, 2018, '1738 Tomscot Center', 'Bulri', '47361');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3119, 2019, '84 Merry Hill', 'Tawau', '91010');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3120, 2020, '9908 Barnett Lane', 'Paty do Alferes', '26950-000');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3121, 2021, '532 Susan Road', 'Virbalis', '70061');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3122, 2022, '3 Northwestern Alley', 'Tabogon', '6009');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3123, 2023, '42 Lyons Court', 'Baratleke', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3124, 2024, '12 Maple Point', 'Urdaneta', '2428');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3125, 2025, '083 Anhalt Road', 'El Quiteño', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3126, 2026, '9926 Luster Parkway', 'Daugai', '64009');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3127, 2027, '5241 Division Park', 'Salitrillos', '10607');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3128, 2028, '9851 Briar Crest Point', 'Sakai-nakajima', '379-2306');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3129, 2029, '5 Cascade Terrace', 'Daloa', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3130, 2030, '0972 Thierer Pass', 'Kitami', '157-0067');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3131, 2031, '370 Fulton Terrace', 'Solnice', '517 01');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3132, 2032, '80 Glendale Lane', 'Meilin', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3133, 2033, '01 Columbus Crossing', 'Florentino Ameghino', '9113');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3134, 2034, '00 Parkside Street', 'Marabahan', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3135, 2035, '27 Monument Place', 'Sokółka', '16-101');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3136, 2036, '9692 Blackbird Circle', 'Oxelösund', '613 81');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3137, 2037, '0 Mosinee Drive', 'Pico da Pedra', '9600-052');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3138, 2038, '39764 Ridgeview Place', 'Danxi', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3139, 2039, '8 Killdeer Trail', 'Jangkungkusumo', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3140, 2040, '72 6th Hill', 'Kotadukuh', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3141, 2041, '5843 Superior Alley', 'Corga', '4960-330');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3142, 2042, '61 Pine View Alley', 'Kálymnos', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3143, 2043, '9 Miller Way', 'Villasis', '2427');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3144, 2044, '4838 Cottonwood Plaza', 'Bandera', '3064');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3145, 2045, '77 Hauk Road', 'Mendeleyevsk', '423650');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3146, 2046, '2744 International Point', 'Pļaviņas', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3147, 2047, '63 Merry Drive', 'New Orleans', '70187');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3148, 2048, '72 Luster Court', 'Laoliangcang', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3149, 2049, '77 Lunder Alley', 'Omigawa', '289-0313');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3150, 2050, '5 Loftsgordon Center', 'Lynn', '01905');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3151, 2051, '062 Lotheville Way', 'Douala', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3152, 2052, '1 Algoma Way', 'Cogreg Wetan', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3153, 2053, '13829 Prairie Rose Way', 'Milano', '20136');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3154, 2054, '57080 Milwaukee Road', 'Seseng', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3155, 2055, '02019 Manley Terrace', 'Nangong', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3156, 2056, '255 Merchant Terrace', 'Dongtou', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3157, 2057, '2 Roxbury Crossing', 'Fonte', '4615-099');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3158, 2058, '7 La Follette Parkway', 'Muravlenko', '102293');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3159, 2059, '550 Kennedy Park', 'San Francisco', '94159');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3160, 2060, '9 Mosinee Avenue', 'Musanze', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3161, 2061, '4904 Leroy Pass', 'Gościeradów', '23-231');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3162, 2062, '29 Hoffman Park', 'La Libertad', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3163, 2063, '921 Tennessee Pass', 'Stockholm', '103 98');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3164, 2064, '07 Lindbergh Alley', 'Kurjan', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3165, 2065, '342 Melvin Plaza', 'La Falda', '4640');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3166, 2066, '20 Sycamore Hill', 'Miguel Hidalgo', '37487');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3167, 2067, '83876 Scoville Point', 'Šid', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3168, 2068, '5405 Hanover Point', 'Barra Mansa', '27300-000');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3169, 2069, '259 Kropf Road', 'Capela', '4960-320');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3170, 2070, '4477 Thompson Place', 'Sebewe', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3171, 2071, '787 Evergreen Point', 'Anao', '2310');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3172, 2072, '8 Express Center', 'Kobryn', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3173, 2073, '55 Huxley Hill', 'Cabaret', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3174, 2074, '62 1st Alley', 'Levandeira', '4635-207');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3175, 2075, '63406 Havey Drive', 'Zhaocun', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3176, 2076, '72861 Mosinee Drive', 'Drawno', '73-220');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3177, 2077, '602 Warbler Alley', 'Ludvika', '771 31');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3178, 2078, '2928 Schlimgen Plaza', 'Mountain View', '94042');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3179, 2079, '9032 Debs Trail', 'Ryazanskaya', '352613');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3180, 2080, '4772 Rowland Point', 'Yelan’-Kolenovskiy', '152720');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3181, 2081, '19 Acker Street', 'Kamphaeng Phet', '44190');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3182, 2082, '6519 Sachs Crossing', 'Färgelanda', '458 31');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3183, 2083, '154 Marcy Pass', 'Ntoum', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3184, 2084, '3 Karstens Parkway', 'Umm Kaddadah', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3185, 2085, '9 Bobwhite Center', 'Artsvanist', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3186, 2086, '524 Hoard Circle', 'Mojo', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3187, 2087, '2759 Katie Way', 'Yoro', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3188, 2088, '9 Dawn Alley', 'Liucheng', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3189, 2089, '5 Alpine Trail', 'Bugko', '6417');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3190, 2090, '20 Scoville Drive', 'Preserje pri Radomljah', '1241');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3191, 2091, '58136 Bayside Circle', 'Staryy Merchyk', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3192, 2092, '191 Northwestern Hill', 'Danyang', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3193, 2093, '9312 Merchant Drive', 'Nakovo', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3194, 2094, '04 Forest Run Pass', 'Quimbaya', '634027');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3195, 2095, '621 Bay Center', 'Poá', '08550-000');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3196, 2096, '657 Jenna Park', 'Moch', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3197, 2097, '154 Cambridge Drive', 'Belogorskīy', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3198, 2098, '9295 Mcbride Park', 'Tabou', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3199, 2099, '28976 Gulseth Alley', 'Strenči', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3200, 2100, '71 Oriole Court', 'Laju Kidul', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3201, 2001, '31718 Lerdahl Avenue', 'Chiba', '427-0001');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3202, 2002, '09 Northfield Circle', 'Babak', '8118');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3203, 2003, '499 Dovetail Pass', 'Suwangi Utara', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3204, 2004, '175 Warrior Center', 'Calçada', '4615-467');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3205, 2005, '2 School Pass', 'Plumbangan', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3206, 2006, '61 6th Parkway', 'Presa', '3070-385');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3207, 2007, '74 Service Circle', 'Olhos de Água', '2950-682');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3208, 2008, '3 Harbort Crossing', 'Vittel', '88804 CEDEX');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3209, 2009, '273 Grover Pass', 'El Cantón', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3210, 2010, '5001 Stang Plaza', 'Yangsan', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3211, 2011, '897 Monica Center', 'Urbiztondo', '2414');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3212, 2012, '19 Aberg Trail', 'Lincoln', '68505');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3213, 2013, '44 Rigney Hill', 'Polykárpi', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3214, 2014, '4 Maple Street', 'Reiko', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3215, 2015, '5319 Homewood Crossing', 'Nguluhan', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3216, 2016, '275 Gerald Road', 'Gent', '9052');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3217, 2017, '9766 Mallard Junction', 'Vetlanda', '574 35');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3218, 2018, '6672 Shopko Park', 'Bålsta', '746 40');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3219, 2019, '918 Old Shore Trail', 'Yartsevo', '215807');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3220, 2020, '432 Buena Vista Alley', 'Taoyuan', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3221, 2021, '6 Utah Circle', 'Iles', '523068');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3222, 2022, '600 Shelley Road', 'Hövsan', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3223, 2023, '6 Declaration Drive', 'Malko Tŭrnovo', '8359');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3224, 2024, '995 Fair Oaks Hill', 'Vatutine', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3225, 2025, '143 Muir Crossing', 'Wattala', '11104');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3226, 2026, '6 Oneill Lane', 'Monte de Trigo', '7220-205');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3227, 2027, '91518 Dawn Pass', 'Malawa', '2417');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3228, 2028, '90 Lunder Crossing', 'Cabaret', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3229, 2029, '80326 Oxford Crossing', 'Bokoro', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3230, 2030, '16328 Talmadge Drive', 'Káto Dhiminió', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3231, 2031, '34354 Utah Court', 'Charenton-le-Pont', '94675 CEDEX');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3232, 2032, '65376 Shopko Parkway', 'Gradil', '2665-105');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3233, 2033, '85 Mayfield Parkway', 'Phoenix', '85025');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3234, 2034, '62899 Haas Center', 'Jiawu', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3235, 2035, '6 Menomonie Avenue', 'Cielądz', '96-214');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3236, 2036, '77723 Bayside Street', 'Sukamaju', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3237, 2037, '3503 John Wall Lane', 'Staraya Stanitsa', '396458');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3238, 2038, '49240 Eggendart Trail', 'El Zulia', '545518');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3239, 2039, '697 Briar Crest Junction', 'Conceição do Coité', '48730-000');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3240, 2040, '50681 Vermont Way', 'Jedlińsk', '26-660');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3241, 2041, '172 Westport Park', 'Otradnoye', '187332');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3242, 2042, '35447 Center Point', 'Wieczfnia Kościelna', '06-513');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3243, 2043, '292 Hoffman Lane', 'Lebyazh’ye', '641500');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3244, 2044, '34 Emmet Park', 'Serra Talhada', '56900-000');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3245, 2045, '8 Charing Cross Point', 'Ранковце', '1316');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3246, 2046, '839 Dwight Way', 'Baku', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3247, 2047, '03 Bunting Plaza', 'Starominskaya', '353617');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3248, 2048, '74 Brentwood Plaza', 'Hyesan-si', null);
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3249, 2049, '8400 Forest Dale Circle', 'Novomoskovsk', '301767');
insert into people_addresses (address_id, person_id, address, city, postal_code) values (3250, 2050, '420 American Ash Pass', 'Rodnikovskaya', '357565');
